name: flutterapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  image_network: ^2.6.0
  excel: ^4.0.6
  file_picker: ^8.1.7
  path_provider: ^2.1.5
  excel_to_json: ^1.4.0
  printing: ^5.13.4
  pdf: ^3.11.1
  http: ^1.2.2
  html: ^0.15.5
  intl: ^0.20.1
  khmer_fonts: ^0.0.6
  image_picker: ^1.1.2
  image_cropper: ^8.0.1
  google_fonts: ^6.1.0
  flutter_widget_from_html: ^0.15.3
  js: ^0.7.1
  flutter_js: ^0.8.1
  ffi: ^2.1.3
  hover_menu: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/fonts/

  fonts:
    - family: NotoSansKhmer
      fonts:
        - asset: assets/fonts/noto/NotoSansKhmer-SemiBold.ttf
        - asset: assets/fonts/noto/NotoSansKhmer-Medium.ttf
        - asset: assets/fonts/noto/NotoSansKhmer-Regular.ttf
        - asset: assets/fonts/noto/NotoSansKhmer-Bold.ttf
    - family: KhmerOs
      fonts:
        - asset: assets/fonts/khmerOs/KhmerOSBattambang-Bold.ttf
        - asset: assets/fonts/khmerOs/KhmerOSBattambang-Regular.ttf
        - asset: assets/fonts/khmerOs/KhmerOSContent-Bold.ttf
        - asset: assets/fonts/khmerOs/KhmerOSContent-Regular.ttf
